[package]
name = "todo"
version = "0.0.1"
edition = "2024"

[dependencies]
colored = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
clap_complete = "4.5"
comfy-table = "6"
